//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod channel;
pub mod friend_requests;
pub mod friendships;
pub mod server;
pub mod user;
pub mod users_channels;
pub mod users_servers;
