//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::channel::Entity as Channel;
pub use super::friend_requests::Entity as FriendRequests;
pub use super::friendships::Entity as Friendships;
pub use super::server::Entity as Server;
pub use super::user::Entity as User;
pub use super::users_channels::Entity as UsersChannels;
pub use super::users_servers::Entity as UsersServers;
